selected_scheme scheme-basic
TEXDIR /tmp/texlive
TEXMFLOCAL /tmp/texlive/texmf-local
TEXMFSYSCONFIG /tmp/texlive/texmf-config
TEXMFSYSVAR /tmp/texlive/texmf-var
TEXMFHOME $TEXMFLOCAL
TEXMFCONFIG $TEXMFSYSCONFIG
TEXMFVAR $TEXMFSYSVAR
instopt_portable 1
tlpdbopt_autobackup 0
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0
