selected_scheme scheme-basic
TEXDIR /texlive
TEXMFCONFIG /.texlive/texmf-config
TEXMFHOME /texmf
TEXMFLOCAL /texlive/texmf-local
TEXMFSYSCONFIG /texlive/texmf-config
TEXMFSYSVAR /texlive/texmf-var
TEXMFVAR /.texlive/texmf-var
binary_win32 1
option_doc 0
option_src 0
