selected_scheme scheme-basic
collection-basic 1
collection-bibtexextra 1
collection-fontsextra 1
collection-fontsrecommended 1
collection-langchinese 1
collection-latex 1
collection-latexextra 1
collection-latexrecommended 1
collection-mathscience 1
collection-xetex 1
tlpdbopt_autobackup 0
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0
